connector_image: airbyte/source-mailchimp:dev
tests:
  spec:
    - spec_path: "source_mailchimp/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/Lists.json"
      validate_output_from_all_streams: yes
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/Campaigns.json"
      validate_output_from_all_streams: yes
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/Email_activity.json"
      validate_output_from_all_streams: yes
  incremental:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/Lists.json"
      cursor_paths:
        charges: [ "date_created" ]
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/Campaigns.json"
      cursor_paths:
        charges: [ "create_time" ]
  full_refresh:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/Email_activity.json"
